# Generated by Django 4.1.2 on 2022-10-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="movies",
        ),
    ]
